---
- name: Ansible create deployed directories in CAR-CE with_items    
  file:
    path: /home/CAR-CE/{{ item }}
    state: directory
    mode: "0755"
    owner: CAR-CE
    group: CAR-CE
  with_items:
     - 'deployednow'
     - 'deployments'

- name: Create apps directory if it does not exist
  file:
    path: /apps
    state: directory
    mode: "{{ perm }}"
    owner: "{{ username }}"
    group: "{{ username }}"
        
- name: Ansible create multiple directories with_items    
  file:
    path: "/apps/{{ item }}"
    state: directory
    mode: "{{ perm }}"
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
     - 'bin'
     - 'cop-claims-cz'      
     - 'cop-claims-iberia'      
     - 'cop-genome'
     - 'cop-idp-necst'
     - 'cop-idp-necst-message-broker'
     - 'cop-income-protection-de'
     - 'cop-mopro'
     - 'cop-mopro-message-broker'
     - 'cop-tma'
     - 'data'
     - 'lib'
     - 'ssl'
